#ifndef FILENAMES_HPP
	#define FILENAMES_HPP

		#define FILEPATH "data/"

		// Fonts:
			#define FILENAME_FONT_MODENINE		FILEPATH "modenine.ttf"
			#define FILENAME_FONT_XENOSPHERE	FILEPATH "xenosphere.ttf"

		// Pictures:
			#define FILENAME_ICON FILEPATH "icon.png"

		// Sound effects:
			#define FILENAME_SOUND_ABSORB				FILEPATH "absorb.wav"
			#define FILENAME_SOUND_ALARM				FILEPATH "alarm.wav"
			#define FILENAME_SOUND_AVALANCHE			FILEPATH "avalanche.wav"
			#define FILENAME_SOUND_BASE_ATTACK_WARNING	FILEPATH "baseattackwarning.wav"
			#define FILENAME_SOUND_BLACKHOLE_CREATED	FILEPATH "blackholecreated.wav"
			#define FILENAME_SOUND_BOULDER				FILEPATH "boulder.wav"
			#define FILENAME_SOUND_BOUNCE				FILEPATH "bounce.wav"
			#define FILENAME_SOUND_BUILDING_EXPLODE		FILEPATH "building_explode.wav"
			#define FILENAME_SOUND_BULLETHIT			FILEPATH "bullethit.wav"
			#define FILENAME_SOUND_BUY					FILEPATH "buy.wav"
			#define FILENAME_SOUND_CRASH				FILEPATH "crash.wav"
			#define FILENAME_SOUND_DIESELMOTOR			FILEPATH "dieselmotor.wav"
			#define FILENAME_SOUND_ELECTRO				FILEPATH "electro.wav"
			#define FILENAME_SOUND_EMP					FILEPATH "emp.wav"
			#define FILENAME_SOUND_ENDGAME				FILEPATH "endgame.wav"
			#define FILENAME_SOUND_EXPLOSION			FILEPATH "explosion.wav"
			#define FILENAME_SOUND_EXTRALIFE			FILEPATH "extralife.wav"
			#define FILENAME_SOUND_FIRE					FILEPATH "fire.wav"
			#define FILENAME_SOUND_FREEZE				FILEPATH "freeze.wav"
			//#define FILENAME_SOUND_FREEZER			FILEPATH "freezer.wav"
			#define FILENAME_SOUND_GRIND				FILEPATH "grind.wav"
			#define FILENAME_SOUND_HEAL					FILEPATH "heal.wav"
			#define FILENAME_SOUND_HOLOGRAM				FILEPATH "hologram.wav"
			#define FILENAME_SOUND_IMPLOSION			FILEPATH "implosion.wav"
			#define FILENAME_SOUND_ITEM_CRUSHED			FILEPATH "itemcrushed.wav"
			#define FILENAME_SOUND_JETENGINE			FILEPATH "jetengine.wav"
			#define FILENAME_SOUND_LADDERS				FILEPATH "ladders.wav"
			#define FILENAME_SOUND_LIFESTEAL			FILEPATH "lifesteal.wav"
			#define FILENAME_SOUND_MINIMISSILE			FILEPATH "minimissile.wav"
			#define FILENAME_SOUND_MINITORPEDO			FILEPATH "minitorpedo.wav"
			#define FILENAME_SOUND_MISSILE				FILEPATH "missile.wav"
			#define FILENAME_SOUND_MOEBIUS				FILEPATH "moebius.wav"
			#define FILENAME_SOUND_NOMONEY				FILEPATH "nomoney.wav"
			#define FILENAME_SOUND_PAINT				FILEPATH "paint.wav"
			#define FILENAME_SOUND_PHASER				FILEPATH "phaser.wav"
			#define FILENAME_SOUND_PROPELLER			FILEPATH "propeller.wav"
			#define FILENAME_SOUND_SABOTAGE				FILEPATH "sabotage.wav"
			#define FILENAME_SOUND_SCREAM				FILEPATH "scream.wav"
			#define FILENAME_SOUND_SELFDESTRUCT			FILEPATH "selfdestruct.wav"
			#define FILENAME_SOUND_SELL					FILEPATH "sell.wav"
			#define FILENAME_SOUND_SHIELD_BOUNCE		FILEPATH "shieldbounce.wav"
			#define FILENAME_SOUND_SHIELD_COLLAPSE		FILEPATH "shieldcollapse.wav"
			#define FILENAME_SOUND_SHOOT				FILEPATH "shoot.wav"
			#define FILENAME_SOUND_SIZER				FILEPATH "sizer.wav"
			#define FILENAME_SOUND_SMOKE				FILEPATH "smoke.wav"
			#define FILENAME_SOUND_STARTGAME			FILEPATH "startgame.wav"
			#define FILENAME_SOUND_STEAL				FILEPATH "steal.wav"
			#define FILENAME_SOUND_TELEPORT				FILEPATH "teleport.wav"
			#define FILENAME_SOUND_TORPEDO				FILEPATH "torpedo.wav"
			#define FILENAME_SOUND_TRACTORBEAM			FILEPATH "tractorbeam.wav"
			#define FILENAME_SOUND_TURBO				FILEPATH "turbo.wav"
			#define FILENAME_SOUND_VOLCANO_ERUPT		FILEPATH "volcanoerupt.wav"
			#define FILENAME_SOUND_WORMHOLE_USED		FILEPATH "wormholeused.wav"
			#define FILENAME_SOUND_YELL					FILEPATH "yell.wav"

		// Music:
			#define FILENAME_MUSIC_TITLE	FILEPATH "Nuggumath-Wings-pelimusa-ReMix_CROPPED.mp3"
			#define FILENAME_MUSIC_GAMEPLAY	FILEPATH "game1.xm"

#endif // FILENAMES_HPP
